apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      initContainers:
        - name: init-kafka
          image: confluentinc/cp-kafka:7.4.0
          command:
            - /bin/bash
            - -c
            - |
              echo "Generating cluster ID..."
              CLUSTER_ID=$(/usr/bin/kafka-storage random-uuid)

              echo "Cluster ID: $CLUSTER_ID"

              cat <<EOF > /etc/kafka/server.properties
              process.roles=broker,controller
              node.id=1
              
              controller.quorum.voters=1@kafka:29093
              controller.listener.names=CONTROLLER
              
              listeners=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093
              advertised.listeners=PLAINTEXT://kafka:9092
              
              listener.security.protocol.map=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
              listener.name.controller.controller.listener.protocol=PLAINTEXT
              
              inter.broker.listener.name=PLAINTEXT
              
              log.dirs=/var/lib/kafka/data/logs
              metadata.log.dir=/var/lib/kafka/data/metadata
              
              offsets.topic.replication.factor=1
              transaction.state.log.replication.factor=1
              transaction.state.log.min.isr=1
              EOF

              echo "Formatting metadata log..."
              /usr/bin/kafka-storage format \
                --config /etc/kafka/server.properties \
                --cluster-id $CLUSTER_ID \
                --ignore-formatted
          volumeMounts:
            - name: kafka-config
              mountPath: /etc/kafka
            - name: kafka-data
              mountPath: /var/lib/kafka/data
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-pvc
        - name: kafka-config
          emptyDir: { }

      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.4.0
          command:
            - /bin/bash
            - -c
            - |
              echo "Starting Kafka..."
              /usr/bin/kafka-server-start /etc/kafka/server.properties
          ports:
            - containerPort: 9092
            - containerPort: 29093
          volumeMounts:
            - name: kafka-config
              mountPath: /etc/kafka
            - name: kafka-data
              mountPath: /var/lib/kafka/data
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - name: broker
      port: 9092
      targetPort: 9092
    - name: controller
      port: 29093
      targetPort: 29093
