global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "user-manager"
    static_configs:
      - targets: ["user-manager:5003"]

  - job_name: "data-collector"
    static_configs:
      - targets: ["data-collector:5002"]

  - job_name: "alert-system"
    static_configs:
      - targets: [ "alert-system:5004" ]
