apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-system
  labels:
    app: alert-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-system
  template:
    metadata:
      labels:
        app: alert-system
    spec:
      containers:
        - name: alert-system
          image: docker.io/local/alert-system:v1
          env:
            - name: KAFKA_BROKER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_BROKER
          ports:
            - containerPort: 5004
              name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: alert-system
spec:
  selector:
    app: alert-system
  ports:
    - name: metrics
      port: 5004
      targetPort: 5004
