apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-notifier
  namespace: dsbd-hw3
  labels:
    app: alert-notifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-notifier
  template:
    metadata:
      labels:
        app: alert-notifier
    spec:
      containers:
        - name: alert-notifier
          image: alert-notifier:hw3
          env:
            - name: KAFKA_BROKER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_BROKER
            - name: SMTP_HOST
              value: "smtp.gmail.com"
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: smtp-user
            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: smtp-pass