apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigw
  labels:
    app: apigw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigw
  template:
    metadata:
      labels:
        app: apigw
    spec:
      containers:
        - name: apigw
          image: docker.io/local/apigw:v1
          ports:
            - containerPort: 8080
            - containerPort: 8443
          imagePullPolicy: Never
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
          # se usi certificati self-signed nel container, puoi montarli qui
      volumes:
        - name: nginx-config
          configMap:
            name: apigw-config
---
apiVersion: v1
kind: Service
metadata:
  name: apigw
spec:
  type: ClusterIP
  selector:
    app: apigw
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443