apiVersion: v1
kind: ConfigMap
metadata:
  name: apigw-config
data:
  routing.conf: |
    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://user-manager:5003;
        }

        location /users {
            proxy_pass http://user-manager:5003/;
        }

        location /data {
            proxy_pass http://data-collector:5002/;
        }
    }

    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate     /etc/nginx/ssl/nginx.selfsigned.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.selfsigned.key;

        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        location / {
            auth_basic "closed site";
            auth_basic_user_file /etc/nginx/htpasswd;
            proxy_pass http://user-manager:5003;
        }

        location /privateUser {
            auth_basic "closed site";
            auth_basic_user_file /etc/nginx/htpasswd;
            proxy_pass http://user-manager:5003/;
        }

        location /privateData {
            auth_basic "closed site";
            auth_basic_user_file /etc/nginx/htpasswd;
            proxy_pass http://data-collector:5002/;
        }
    }