apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigw
  labels:
    app: apigw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigw
  template:
    metadata:
      labels:
        app: apigw
    spec:
      containers:
        - name: apigw
          image: docker.io/local/apigw:v1
          ports:
            - containerPort: 80
            - containerPort: 443
          imagePullPolicy: Never
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: nginx-htpasswd
              mountPath: /etc/nginx/htpasswd
              subPath: htpasswd
            - name: nginx-certs
              mountPath: /etc/nginx/ssl
      volumes:
        - name: nginx-config
          configMap:
            name: apigw-config
        - name: nginx-htpasswd
          secret:
            secretName: apigw-htpasswd
        - name: nginx-certs
          secret:
            secretName: apigw-tls
---
apiVersion: v1
kind: Service
metadata:
  name: apigw
spec:
  type: NodePort
  selector:
    app: apigw
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30443