apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-collector
  labels:
    app: data-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-collector
  template:
    metadata:
      labels:
        app: data-collector
    spec:
      containers:
        - name: data-collector
          image: docker.io/local/data-collector:v1
          ports:
            - containerPort: 5002   # REST
            - containerPort: 50052  # gRPC
          env:
            - name: MYSQL_HOST
              value: "data-db"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: mysql-username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: mysql-password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MYSQL_DATA_DB
            - name: LISTEN_PORT
              value: "5002"
            - name: LISTEN_PORT_GRPC
              value: "50052"
            - name: GRPC_HOST
              value: "user-manager"
            - name: GRPC_SEND_PORT
              value: "50051"
            - name: OPENSKY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: opensky-client-id
            - name: OPENSKY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: opensky-client-secret
            - name: KAFKA_BROKER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_BROKER
            - name: SERVICE_NAME
              value: "data-collector"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
---
apiVersion: v1
kind: Service
metadata:
  name: data-collector
spec:
  selector:
    app: data-collector
  ports:
    - name: http
      port: 5002
      targetPort: 5002
    - name: grpc
      port: 50052
      targetPort: 50052
