apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  mysql-root-password: "toor"
  mysql-username: "urzrus"
  mysql-password: "rusurz"

  opensky-client-id: "urzim-api-client"
  opensky-client-secret: "wtIMZy1cpjr7BCNTa4TCFcHyIydQKCIW"

  smtp-user: "russurzimartani@gmail.com"
  smtp-pass: "sfyi dpji ryog dttu"

  jwt-secret: "aac4e7616ebf951ea0e4e4e0d770f93252564a9ec64be49a45849e91ce198f7d"